# Generated by Django 5.1.4 on 2025-03-07 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_summaries_summarie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Summarie',
            new_name='Summary',
        ),
    ]
