# Generated by Django 5.1.4 on 2025-03-07 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_summary_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
