# Generated by Django 5.1.4 on 2025-03-07 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_summary_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summary',
            options={'ordering': ('-created',), 'verbose_name_plural': 'Summaries'},
        ),
    ]
